### ISSUE TITLE
[Bug] WSL2中无法正常输入文字

### ISSUE THREAD

**Issue by leeyiding** [lobehub/lobe-commit#13]
### 💻 系统环境 | Operating System

Windows

### 🌐 CLI 版本 | CLI Version

2.9.3

### 🐛 问题描述 | Bug Description

WSL2中无法正常输入文字，每当需要输入文字的时候，程序就自动终止了

https://github.com/lobehub/lobe-commit/assets/49098278/dd7b25e1-593c-4d47-ad9e-f55c88d318b9

```
> uname -a  
Linux DESKTOP-C9MSV31 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

> node -v                                
v18.16.0

> lobe-commit -V
2.9.3
```

**Comment by canisminor1990** [comment]
之前的这个问题是由于 Ink 版本导致的，其实在 2.9.3 中已经修复了这个问题，目前在 Mac 和 Win 中测试通过， WSL2 中还没有测试

**Comment by leeyiding** [comment]
尝试重新全局安装了几次，成功解决了，谢谢！
